version: '3'

services:
  mariadb:
    build: ./db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=sws
    # volumes:
    #   - mariadb_data:/bitnami
    ports:
      - '3306:3306'
    networks:
      - nesjs-network

  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:


# volumes:
#   mariadb_data:
#     driver: local