version: '3'
name: rbac-dev

services:
  rbac:
    image: nestjs-container:latest
    command: yarn start # tail -f /dev/null
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - rbac-network
    working_dir: /usr/src/app

  mariadb:
    build: ./db
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
      - MYSQL_DATABASE=rbac
    volumes:
      - ./volumes/db/bitnami:/bitnami
    ports:
      - '3306:3306'
    networks:
      - rbac-network

networks:
  rbac-network:

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  mongo-data:
    driver: local
